pipeline {
	agent any

	tools {

		maven 'Apache Maven 3.0.5'
	}

	stages {

		stage('Checkout Simple-Java-App from GitHub') {
			steps {
				checkout(
					[
						$class: 'GitSCM',
						branches: [[name: '*/master']],
						doGenerateSubmoduleConfigurations: false,
						extensions: [],
						submoduleCfg: [],
						userRemoteConfigs: [[url: 'git@github.com:jenkins-docs/simple-java-maven-app.git']]
					]
				)
			}
		}

		stage('Build') {
			steps {
				sh 'mvn -B -DskipTests clean package'
			}
		}

		stage('Test') {
			steps {
				echo 'Testing...'
			}
		}

		stage('Deploy') {
			steps {
				echo 'Deploying...'
			}
		}
	}	
}